---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: src/posts
  label: Blog Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: heading
  label: Pages
- type: document
  path: src/pages/about.md
  label: About
- type: document
  path: src/pages/contact.md
  label: Contact
- type: document
  path: src/404.md
  label: '404'
- type: document
  path: src/index.md
  label: Home
- type: document
  path: src/posts.md
  label: Posts
- type: heading
  label: Global
- type: document
  path: src/_data/navigation.json
  label: Navigation
- type: document
  path: src/_data/tokens.json
  label: Theme settings
upload_dir: src/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - ELEVENTY_ENV=staging
  preview_output_directory: src/dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
